# Generated by Django 5.1.3 on 2024-12-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('rol', models.CharField(max_length=30)),
            ],
        ),
    ]
