# Generated by Django 5.1.3 on 2024-12-08 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citas',
            options={'verbose_name': 'Cita', 'verbose_name_plural': 'Cita'},
        ),
        migrations.AlterField(
            model_name='citas',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
