# Generated by Django 5.1.3 on 2024-12-10 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_citas_options_alter_citas_id_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='id_usuario',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
