# Generated by Django 5.1.3 on 2024-12-11 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_alter_citas_id_usuario'),
        ('dentista', '0002_dentista_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='id_dentista',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='dentista.dentista', verbose_name='Dentista'),
        ),
    ]
